--table pedidos
drop table if exists pedidos;

CREATE TABLE pedidos (
	ano_mes DECIMAL ,
	tipo_movimento DECIMAL ,
	centro DECIMAL ,
	nr_utente DECIMAL ,
	cnp_pretendida DECIMAL ,
	ind_cnp DECIMAL ,
	cae_anterior_v2 VARCHAR,
	ind1_cae_v2 VARCHAR,
	ind2_cae_v2 VARCHAR,
	data_movimento TIMESTAMP WITHOUT TIME ZONE,
	freguesia VARCHAR ,
	nacionalidade VARCHAR ,
	idade DECIMAL ,
	sexo VARCHAR ,
	habilitacao VARCHAR ,
	pais_emigracao VARCHAR,
	deficiencia DECIMAL ,
	categoria DECIMAL ,
	motivo_inscricao DECIMAL ,
	rinsc VARCHAR ,
	estado_civil VARCHAR ,
	nr_pessoas_cargo DECIMAL,
	tempo_inscricao DECIMAL ,
	tempo_pratica DECIMAL,
	local_trabalho VARCHAR,
	a_tempo VARCHAR ,
	natureza_emprego VARCHAR ,
	ucnp DECIMAL,
	tempo_pratica_ucnp DECIMAL,
	subsidio VARCHAR,
	cnp_colocacao DECIMAL,
	cae_colocacao_v2 VARCHAR,
	local_colocacao VARCHAR,
	natureza_colocacao VARCHAR,
	data_colocacao TIMESTAMP WITHOUT TIME ZONE,
	data_anulacao TIMESTAMP WITHOUT TIME ZONE,
	motivo_anulacao DECIMAL,
	plano_emprego VARCHAR ,
	ute_id DECIMAL ,
	rmg VARCHAR ,
	centro_movimento DECIMAL ,
	data_inscricao TIMESTAMP WITHOUT TIME ZONE,
	data_nascimento TIMESTAMP WITHOUT TIME ZONE,
	motivo_anterior_saida DECIMAL,
	pais_colocacao VARCHAR,
	regime_trabalho_colocacao VARCHAR,
	qualificacao DECIMAL,
	rmg_anterior VARCHAR ,
	motivo_fim_rmg DECIMAL,
	ppe_anterior VARCHAR ,
	tipo_doc_id VARCHAR ,
	formacao_profissional VARCHAR,
	areas_curso VARCHAR,
	data_prim_candidatura TIMESTAMP WITHOUT TIME ZONE,
	data_n_reinsc TIMESTAMP WITHOUT TIME ZONE,
	motivo_visita DECIMAL ,
	centro_np DECIMAL,
	cod_prog_sief VARCHAR,
	estado VARCHAR ,
	data_ultima_saida TIMESTAMP WITHOUT TIME ZONE,
	origem_candidatura VARCHAR,
	carteira_profissional VARCHAR,
	rsi VARCHAR,
	motivo_indisponibilidade DECIMAL,
	data_fim_indisponivel TIMESTAMP WITHOUT TIME ZONE,
	sd_motivo_desemprego VARCHAR,
	apresentacao_quinzenal VARCHAR ,
	pae VARCHAR ,
	declaracao_ent_empregadora VARCHAR,
	advert_notif VARCHAR,
	tipo_notificacao_ocorrencia VARCHAR,
	tipo_resultado_notificacao VARCHAR,
	cest_superior DECIMAL,
	ano_conclusao_curso DECIMAL,
	recrutamento_internacional VARCHAR,
	data_rec_internacional VARCHAR,
	tipo_actividade VARCHAR,
	utilizador VARCHAR,
	cae_anterior DECIMAL,
	ind1_cae DECIMAL,
	ind2_cae DECIMAL,
	cae_colocacao DECIMAL,
	id_conjuge VARCHAR,
	estado_civ_conjuge VARCHAR,
	categoria_conjuge VARCHAR,
	estado_conjuge VARCHAR,
	motiv_indisp_conjuge VARCHAR,
	tipo_ocupacao VARCHAR,
	data_desemprego VARCHAR,
	categoria_anterior VARCHAR,
	estado_anterior VARCHAR,
	cod_intervencao VARCHAR,
	ccrss VARCHAR,
	motivo_indisponibilidade_ant VARCHAR,
	me2012 VARCHAR,
	id_estabel VARCHAR,
	id_oferta VARCHAR,
	data_subsidio VARCHAR,
	descendentes_a_cargo VARCHAR,
	subsidio_conjuge VARCHAR,
	regime_horario VARCHAR,
	sub_decreto_lei VARCHAR,
	sub_data_indef VARCHAR,
	sub_data_inicio VARCHAR,
	sub_data_fim VARCHAR,
	sub_tempo_previsto VARCHAR,
	sub_valor VARCHAR,
	sub_data_extincao VARCHAR,
	sub_data_suspensao VARCHAR,
	sub_data_reinicio VARCHAR,
	sub_cod_motivo_cessacao VARCHAR,
	sub_cod_motivo_suspensao VARCHAR,
	gestor_carreira VARCHAR,
	segmento VARCHAR,
	data_afetacao_tecnico VARCHAR,
	origem_registo_utente VARCHAR,
	motivo_invalidacao VARCHAR,
	data_elaboracao_ppe VARCHAR,
	centroa VARCHAR,
	num_pedidos_esclar VARCHAR,
	data_pedido_ult_ped_esclar VARCHAR,
	data_resposta_ult_ped_esclar VARCHAR,
	me2013 VARCHAR,
	reembolso_tsu VARCHAR,
	tempo_pratica_ucpp VARCHAR,
	ucpp VARCHAR,
	cpp_pretendida VARCHAR,
	ind_cpp VARCHAR,
	cpp_colocacao VARCHAR,
	enicc VARCHAR,
	gj VARCHAR,
	data_inicio_gj VARCHAR,
	data_primeira_resposta_gj VARCHAR,
	gj_anterior VARCHAR,
	motivo_nao_sinalizacao_gj VARCHAR,
	motivo_fim_gj VARCHAR,
	data_fim VARCHAR,
	me2014 VARCHAR,
	primeira_resposta_tie_cod_gj VARCHAR,
	data_ultimo_contacto VARCHAR,
	tuc_codigo VARCHAR,
	eao VARCHAR,
	e_mais VARCHAR,
	feg VARCHAR,
	tipo_feg VARCHAR,
	rp VARCHAR,
	nce_cnacionalidade_rp VARCHAR,
	pais_residencia_estrang VARCHAR,
	grau_habilitacao_estrang VARCHAR,
	last_update_date VARCHAR
);

\copy pedidos from './data/EMP_PEDIDOS.csv' with csv header; --37,317,447

CREATE INDEX pedidos_idx_ute_id on pedidos(ute_id);
CREATE INDEX pedidos_idx_data_movimento on pedidos(data_movimento);
CREATE INDEX pedidos_idx_ute_id_data_movimento on pedidos(ute_id, data_movimento);
CREATE INDEX pedidos_idx_ano_mes on pedidos(ano_mes);
CREATE INDEX pedidos_idx_tipo_movimento on pedidos(tipo_movimento);
CREATE INDEX pedidos_idx_sexo on pedidos(sexo);
CREATE INDEX pedidos_idx_centro on pedidos(centro);

--table intervencoes
DROP TABLE IF EXISTS intervencoes;

CREATE TABLE intervencoes (
	ano_mes DECIMAL ,
	tipo_movimento DECIMAL ,
	centro DECIMAL ,
	nr_utente DECIMAL ,
	codigo_intervencao DECIMAL ,
	data_intervencao TIMESTAMP WITHOUT TIME ZONE,
	sessao DECIMAL,
	area_intervencao DECIMAL,
	data_resultado TIMESTAMP WITHOUT TIME ZONE,
	resultado_intervencao DECIMAL,
	data_movimento TIMESTAMP WITHOUT TIME ZONE,
	freguesia VARCHAR ,
	idade VARCHAR ,
	sexo VARCHAR ,
	habilitacao VARCHAR ,
	ppe VARCHAR ,
	categoria DECIMAL,
	cnp_pretendida DECIMAL,
	tempo_inscricao DECIMAL,
	tipo_utente VARCHAR ,
	ute_id DECIMAL ,
	rmg VARCHAR ,
	centro_movimento VARCHAR ,
	data_nascimento TIMESTAMP WITHOUT TIME ZONE,
	data_inscricao TIMESTAMP WITHOUT TIME ZONE,
	nacionalidade VARCHAR ,
	deficiencia DECIMAL ,
	rmg_anterior VARCHAR ,
	motivo_fim_rmg DECIMAL,
	estado_civil VARCHAR ,
	nr_pessoas_cargo DECIMAL,
	cae_anterior_v2 VARCHAR,
	carteira_profissional VARCHAR,
	qualificacao DECIMAL,
	ppe_anterior VARCHAR ,
	cnp_anterior DECIMAL,
	subsidio VARCHAR,
	local_trabalho VARCHAR,
	tipo_candidatura_externa VARCHAR,
	tipo_contrato_pretendido VARCHAR,
	regime_trabalho_pretendido VARCHAR,
	formacao_profissional VARCHAR,
	areas_curso VARCHAR,
	tipo_doc_id VARCHAR ,
	tempo_pratica_ucnp DECIMAL,
	tempo_pratica VARCHAR,
	centro_np VARCHAR,
	estado VARCHAR,
	rsi VARCHAR,
	ambito VARCHAR,
	pri VARCHAR,
	projecto VARCHAR,
	ito_eco VARCHAR ,
	tipo VARCHAR,
	tipo_encaminhamento VARCHAR ,
	ccentro_ins DECIMAL,
	ccentro DECIMAL,
	afirmativo VARCHAR,
	f_dcurso VARCHAR,
	f_horas DECIMAL,
	f_cmod_form DECIMAL,
	f_data_inicio TIMESTAMP WITHOUT TIME ZONE,
	f_data_fim TIMESTAMP WITHOUT TIME ZONE,
	f_ccurso VARCHAR,
	f_dmod_form VARCHAR,
	motivo_enc VARCHAR,
	f_situacao VARCHAR,
	f_carea_form DECIMAL,
	f_darea_form VARCHAR,
	revalidacao VARCHAR,
	f_vagas DECIMAL,
	f_vagas_ocupadas DECIMAL,
	motivo_recusa VARCHAR,
	sd_motivo_desemprego VARCHAR,
	apresentacao_quinzenal VARCHAR ,
	pae VARCHAR ,
	cest_superior DECIMAL,
	ano_conclusao_curso DECIMAL,
	utilizador VARCHAR ,
	cae_anterior DECIMAL,
	cod_req_rsi VARCHAR,
	f_cno_npc VARCHAR,
	f_cno_sub_ent VARCHAR,
	tipo_ocupacao VARCHAR,
	data_desemprego VARCHAR,
	id_interv_encaminh VARCHAR,
	data_subsidio VARCHAR,
	ito_id VARCHAR,
	id_interv_encaminh_origem VARCHAR,
	codigo_interv_encaminh_origem VARCHAR,
	descendentes_a_cargo VARCHAR,
	subsidio_conjuge VARCHAR,
	pos_laboral VARCHAR,
	tempo_parcial VARCHAR,
	id_conjuge VARCHAR,
	categoria_conjuge VARCHAR,
	estado_conjuge VARCHAR,
	motiv_indisp_conjuge VARCHAR,
	gestor_carreira VARCHAR,
	segmento VARCHAR,
	origem_registo_utente VARCHAR,
	data_afetacao_tecnico VARCHAR,
	data_elaboracao_ppe VARCHAR,
	pertence_ao_ppe VARCHAR,
	centroa VARCHAR,
	cpp_pretendida VARCHAR,
	tempo_pratica_ucpp VARCHAR,
	cpp_anterior VARCHAR,
	f_cno_id_estabel VARCHAR,
	enicc VARCHAR,
	gj VARCHAR,
	data_inicio_gj VARCHAR,
	data_primeira_resposta_gj VARCHAR,
	motivo_nao_sinalizacao_gj VARCHAR,
	tipo_sessao VARCHAR,
	medida_orcamental VARCHAR,
	feg VARCHAR,
	tipo_feg VARCHAR,
	rp VARCHAR,
	nce_cnacionalidade_rp VARCHAR,
	pais_residencia_estrang VARCHAR,
	grau_habilitacao_estrang VARCHAR,
	last_update_date VARCHAR
);

\COPY intervencoes from './data/MOV_INTERVENCOES.csv' with csv header; --44,585,170

CREATE INDEX intervencoes_idx_ute_id on intervencoes(ute_id);
CREATE INDEX intervencoes_idx_ano_mes on intervencoes(ano_mes);
CREATE INDEX intervencoes_idx_data_movimento on intervencoes(data_movimento);
CREATE INDEX intervencoes_idx_estado on intervencoes(estado);
CREATE INDEX intervencoes_idx_tipo_movimento on intervencoes(tipo_movimento);
CREATE INDEX intervencoes_idx_ute_id on intervencoes(ute_id);

